const categories = [
  { id: 'video', name: '一起看', icon: '🎬', subtitle: '今晚看什么' },
  { id: 'dessert', name: '甜点', icon: '🍰', subtitle: '甜一点点' },
  { id: 'drink', name: '饮料', icon: '🥤', subtitle: '碰杯时刻' },
  { id: 'meal', name: '正餐', icon: '🍝', subtitle: '认真吃饭' },
  { id: 'snack', name: '小食', icon: '🍿', subtitle: '边聊边吃' },
  { id: 'surprise', name: '小惊喜', icon: '💐', subtitle: '为爱加餐' },
];

const coupleProfile = {
  anniversary: '2025-07-30',
  herName: '小可爱',
  hisName: '大朋友',
  message: '把普通的一天，过成喜欢的样子。',
};

const menuItems = [
  {
    id: 'video-01',
    categoryId: 'video',
    name: '治愈电影夜',
    description: '一部轻松电影 + 不许玩手机',
    image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=900&q=80',
    cost: '你来选片',
    badge: '本周热门',
  },
  {
    id: 'video-02',
    categoryId: 'video',
    name: '悬疑追剧局',
    description: '选一部烧脑新剧，一起猜结局',
    image: 'https://images.unsplash.com/photo-1574267432553-4b4628081c31?auto=format&fit=crop&w=900&q=80',
    cost: '猜错的人请奶茶',
    badge: '默契挑战',
  },
  {
    id: 'dessert-01',
    categoryId: 'dessert',
    name: '莓果奶油蛋糕',
    description: '酸甜莓果与轻盈奶油，分享刚刚好',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=80',
    cost: '一个抱抱',
    badge: '心动推荐',
  },
  {
    id: 'dessert-02',
    categoryId: 'dessert',
    name: '焦糖巴斯克',
    description: '浓郁芝士，焦香微苦不腻口',
    image: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=900&q=80',
    cost: '下次你来选',
    badge: '',
  },
  {
    id: 'drink-01',
    categoryId: 'drink',
    name: '草莓气泡水',
    description: '清爽气泡与新鲜草莓，今日份粉色',
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=900&q=80',
    cost: '说一句夸夸',
    badge: '少女心',
  },
  {
    id: 'drink-02',
    categoryId: 'drink',
    name: '双份热可可',
    description: '两杯暖暖的可可，奶油半糖',
    image: 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?auto=format&fit=crop&w=900&q=80',
    cost: '一起拍张照',
    badge: '两人份',
  },
  {
    id: 'meal-01',
    categoryId: 'meal',
    name: '奶油蘑菇意面',
    description: '奶香浓郁，蘑菇与黑胡椒的经典搭配',
    image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=80',
    cost: '吃完你洗碗',
    badge: '',
  },
  {
    id: 'meal-02',
    categoryId: 'meal',
    name: '周末披萨派对',
    description: '双拼口味，留一块给最喜欢的人',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=80',
    cost: '下次换我请',
    badge: '约会必点',
  },
  {
    id: 'snack-01',
    categoryId: 'snack',
    name: '焦糖爆米花',
    description: '电影开场前的甜蜜仪式感',
    image: 'https://images.unsplash.com/photo-1578849278619-e73505e9610f?auto=format&fit=crop&w=900&q=80',
    cost: '靠在一起看',
    badge: '',
  },
  {
    id: 'snack-02',
    categoryId: 'snack',
    name: '脆薯分享盒',
    description: '一大盒金黄脆薯，配两种蘸酱',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=80',
    cost: '最后一根归我',
    badge: '分享装',
  },
  {
    id: 'surprise-01',
    categoryId: 'surprise',
    name: '今日份鲜花',
    description: '无需节日，也可以送一束花',
    image: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=900&q=80',
    cost: '一个惊喜',
    badge: '浪漫加倍',
  },
  {
    id: 'surprise-02',
    categoryId: 'surprise',
    name: '手写心意卡',
    description: '认真写下此刻最想说的一句话',
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80',
    cost: '认真读完它',
    badge: '',
  },
];

const featuredIds = ['dessert-01', 'video-01', 'drink-02', 'meal-02'];

module.exports = {
  categories,
  coupleProfile,
  featuredIds,
  featuredItems: featuredIds.map((id) => menuItems.find((item) => item.id === id)),
  menuItems,
};
