/** 推荐分类模板（也会同步到云库 contentTemplates） */
const categoryTemplates = [
  { id: 'tpl-cat-video', name: '一起看', icon: '🎬', subtitle: '今晚看什么', image: '' },
  { id: 'tpl-cat-dessert', name: '甜点', icon: '🍰', subtitle: '甜一点点', image: '' },
  { id: 'tpl-cat-drink', name: '饮料', icon: '🥤', subtitle: '碰杯时刻', image: '' },
  { id: 'tpl-cat-meal', name: '正餐', icon: '🍝', subtitle: '认真吃饭', image: '' },
  { id: 'tpl-cat-snack', name: '小食', icon: '🍿', subtitle: '边聊边吃', image: '' },
  { id: 'tpl-cat-surprise', name: '小惊喜', icon: '💐', subtitle: '为爱加餐', image: '' },
  { id: 'tpl-cat-travel', name: '出去玩', icon: '🚗', subtitle: '说走就走', image: '' },
  { id: 'tpl-cat-home', name: '居家日', icon: '🏠', subtitle: '窝在一起', image: '' },
  { id: 'tpl-cat-sport', name: '运动', icon: '🏸', subtitle: '出出汗', image: '' },
  { id: 'tpl-cat-gift', name: '礼物', icon: '🎁', subtitle: '小小心意', image: '' },
];

/** 推荐点单/心愿模板 */
const menuTemplates = [
  {
    id: 'tpl-menu-movie',
    categoryHint: '一起看',
    name: '治愈电影夜',
    description: '一部轻松电影 + 不许玩手机',
    cost: '你来选片',
    badge: '本周热门',
    image: '',
  },
  {
    id: 'tpl-menu-series',
    categoryHint: '一起看',
    name: '悬疑追剧局',
    description: '选一部烧脑新剧，一起猜结局',
    cost: '猜错的人请奶茶',
    badge: '默契挑战',
    image: '',
  },
  {
    id: 'tpl-menu-cake',
    categoryHint: '甜点',
    name: '莓果奶油蛋糕',
    description: '酸甜莓果与轻盈奶油，分享刚刚好',
    cost: '一个抱抱',
    badge: '心动推荐',
    image: '',
  },
  {
    id: 'tpl-menu-basque',
    categoryHint: '甜点',
    name: '焦糖巴斯克',
    description: '浓郁芝士，焦香微苦不腻口',
    cost: '下次你来选',
    badge: '',
    image: '',
  },
  {
    id: 'tpl-menu-soda',
    categoryHint: '饮料',
    name: '草莓气泡水',
    description: '清爽气泡与新鲜草莓',
    cost: '说一句夸夸',
    badge: '少女心',
    image: '',
  },
  {
    id: 'tpl-menu-cocoa',
    categoryHint: '饮料',
    name: '双份热可可',
    description: '两杯暖暖的可可，奶油半糖',
    cost: '一起拍张照',
    badge: '两人份',
    image: '',
  },
  {
    id: 'tpl-menu-pasta',
    categoryHint: '正餐',
    name: '奶油蘑菇意面',
    description: '奶香浓郁，蘑菇与黑胡椒',
    cost: '吃完你洗碗',
    badge: '',
    image: '',
  },
  {
    id: 'tpl-menu-pizza',
    categoryHint: '正餐',
    name: '周末披萨派对',
    description: '双拼口味，留一块给最喜欢的人',
    cost: '下次换我请',
    badge: '约会必点',
    image: '',
  },
  {
    id: 'tpl-menu-popcorn',
    categoryHint: '小食',
    name: '焦糖爆米花',
    description: '电影开场前的甜蜜仪式感',
    cost: '靠在一起看',
    badge: '',
    image: '',
  },
  {
    id: 'tpl-menu-fries',
    categoryHint: '小食',
    name: '脆薯分享盒',
    description: '一大盒金黄脆薯，配两种蘸酱',
    cost: '最后一根归我',
    badge: '分享装',
    image: '',
  },
  {
    id: 'tpl-menu-flower',
    categoryHint: '小惊喜',
    name: '今日份鲜花',
    description: '无需节日，也可以送一束花',
    cost: '一个惊喜',
    badge: '浪漫加倍',
    image: '',
  },
  {
    id: 'tpl-menu-letter',
    categoryHint: '小惊喜',
    name: '手写心意卡',
    description: '认真写下此刻最想说的一句话',
    cost: '认真读完它',
    badge: '',
    image: '',
  },
  {
    id: 'tpl-menu-walk',
    categoryHint: '出去玩',
    name: '日落散步',
    description: '晚饭后走一会儿，手牵手即可',
    cost: '听你讲今天',
    badge: '',
    image: '',
  },
  {
    id: 'tpl-menu-massage',
    categoryHint: '居家日',
    name: '肩颈放松',
    description: '认真按十分钟，不许敷衍',
    cost: '下次换我',
    badge: '温柔时刻',
    image: '',
  },
];

module.exports = {
  categoryTemplates,
  menuTemplates,
};
